### ISSUE TITLE
Repository with S3 storage back doesn't work

### ISSUE THREAD

**Issue by g4s8** [artipie/asto#163]
When using S3 storage configuration for repository, the request to Artipie hangs forever and then reset by request timeout. Artipie doesn't print logs about it.
Configuration:
```yaml
# simple file repository
# located at `./tmp/repo/ff.yaml
repo:
  type: file
  storage:
    type: s3
    region: eu-central-1
    url: s3://artipie.test/binary
    endpoint: https://s3.eu-central-1.amazonaws.com
    bucket: artipie.test
    credentials:
      type: basic
      accessKeyId: <id>
      secretAccessKey: <secret>
```
To reproduce I started Docker image: `docker run -v $PWD/tmp:/var/artipie -p80:80 artipie:local` (local I build from the latest master commit with `docker build -t artipie:local .`).
And send HTTP request for upload: `http PUT localhost/ff/hello hello=world`. The same steps working fine with file-system storage.
The result: `http: error: Request timed out (30s).` and nothing in S3 bucket.
